### ISSUE TITLE
Incorrect resource links on the error page during authorization

### ISSUE THREAD

**Issue by twistedfall** [sebadob/rauthy#139]
If you would go to the authorization at `/auth/v1/oidc/authorize` and make an error in the e.g. `redirect_url` like this:
```
http://localhost:8080/auth/v1/oidc/authorize?client_id=rauthy&redirect_uri=http1://localhost:8080/auth/v1/oidc/callback&response_type=code&code_challenge=919cZTslqlJKfD7-ncc5ivtfysYA_O3gy9DMV3Plvu0&code_challenge_method=S256&scope=openid+profile+email&nonce=7qLW7gcA4LhRhchuVL1dlEAM&state=admin
```
Then you are presented with just an empty page. It's happening because all of the `<link>` in the HTML page are addressing resources via `./_app/` (single dot) instead of the correct `../_app/` (double dot).

**Comment by sebadob** [comment]
This is an interesting behavior I never came across.  
Actually, the redirect is currently in the wrong format and needs adoption I do remember now.
`://` should be encoded with `%3A%2F%2`
But even then it behaves the same.

The resource links are auto-generated by the svelte static adapter. I will have a look at this, where this might come from.
I recently added sublinks for all pages so you could actually copy & paste links inside the Admin UI. There might be the reason for this.

**Comment by sebadob** [comment]
This was a bit of a rabbit hole and I found out, that I also had a bug for the user registration page, since it returned the newly introduced E-Mail confirmation page there.
This is all fixed now and I guess I will release a patch version pretty soon.
