### ISSUE TITLE
Error when running just build-ui

### ISSUE THREAD

**Issue by sjud** [sebadob/rauthy#275]
```sh
+ sed -i 's/lang="en"/lang="{{ lang }}"/g' templates/html/account.html
sed: 1: "templates/html/account. ...": undefined label 'emplates/html/account.html'
error: Recipe `build-ui` failed with exit code 1
```

It looks like the files were built
I can see a templates/html/account.html file but no replacement.

```html
<!DOCTYPE html>
<html lang="en">
. . .
```

**Comment by sebadob** [comment]
That's a bit weird.

There is the [CONTRIBUTIND.md](https://github.com/sebadob/rauthy/blob/main/CONTRIBUTING.md) which should help with the dev setup.

On what kind of host are you trying to build?  The only reason I can imagine for now if you would not have BASH available somehow.

**Comment by sjud** [comment]
Yes, it is weird. It actually doesn't interfere with me using the service having built it from source. I do have BASH available, I'm on macOs 11.7.9

**Comment by sebadob** [comment]
I don't own any Mac, so I cannot test stuff there.

Maybe the shebang is a problem on Mac. The current version is more portable, but let's check it anyway.  
Please change the very first line of the `build-ui` recipe to `#!/usr/bin/bash` and try again.

**Comment by sjud** [comment]
https://github.com/sebadob/rauthy/pull/281
