### ISSUE TITLE
New registered user get a `recovery email`

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#317]
After register a new user, the user needs to verify their email. The verification email is the base template for `resetting their password`, which is a little bit confusing for the user. A seperate welcome email would be awesome! :heart:

**Comment by sebadob** [comment]
Yes that's right. They get the same template.
A different one for a "new password" could be sent out depending on if the user has set any password at all or not.

**Comment by kerkmann** [comment]
@sebadob Thanks! You are awesome! :heart:
