### ISSUE TITLE
Feature request: add bootstrapping mechanism that can be automated instead of having to fetch generated password from the logs

### ISSUE THREAD

**Issue by taladar** [sebadob/rauthy#363]
It would be great if rauthy bootstrap could be automated with software like Terraform/OpenTofu, e.g. by passing the initial admin credentials (email, password, possibly an admin API token) as environment variables the way other software does for bootstrap.

That way installing and then configuring rauthy via something like a Terraform provider could be fully automated without any manual steps.

**Comment by sebadob** [comment]
I thought about adding something like this as well, yes.

**Comment by taladar** [comment]
It might be a bit tricky to generate an sqlite DB file with a rauthy specific schema as part of the deployment process.

**Comment by taladar** [comment]
Preparing the file manually might be fine for testing but for something like an instance accessible from the public internet it would be useful if each deployed instance had a distinct, auto-generated password (and API token if that is applicable).

**Comment by sebadob** [comment]
> ...it would be useful if each deployed instance had a distinct, auto-generated password...

This is the case. That's why you see the password in the logs at the very first startup.  
The only use case I see for something like this is when providing an OIDC SaaS.
Where else what you need all of this to be fully automatic and externally handled?

Such a feature will probably come when I start developing the K8s operator at some point.

**Comment by taladar** [comment]
Not really as SaaS. I am currently experimenting with Kubernetes clusters after years of using Puppet for Infrastructure as Code and I am trying to get clusters set up in a fully (apart from specifying some access tokens and names as parameters) automated and repeated way and want to use some OIDC provider in the cluster to protect observability tools like Grafana and Prometheus, ideally something with low resource usage so the VPS used as basis for the Kubernetes cluster do not need to be too large just for that kind of basic cluster infrastructure that every cluster might need.

**Comment by sebadob** [comment]
Ahh I see, okay... yes in that case it makes sense.

I can add something to achieve this before starting with the k8s operator.

**Comment by sebadob** [comment]
You can test with 

```
ghcr.io/sebadob/rauthy:0.22.2-20240424-2-lite
```

if you like.

**Comment by taladar** [comment]
I did test this today and at least the _PLAIN variant seems to work as expected, I haven't been able to find a way to generate the password hash yet so I didn't test the other one.

Now I just need to figure out a way to bootstrap my way from there to an API key automatically to configure the new instance.

**Comment by sebadob** [comment]
> Now I just need to figure out a way to bootstrap my way from there to an API key automatically to configure the new instance.

I could implement another env var which does this. But then you would have to carefully build the JSON object and serialize it into base64, if this would be an option for you. On my side this is not too much work. I just figured that people would not want to do that. :D

**Comment by taladar** [comment]
I would not mind carefully building a JSON object. Would that JSON object include just the permissions or would the actual secret key part of the API key be part of that as well? It might make sense to split them up into two environment variables if that JSON does not already exist on your end since for any given bootstrap you probably want a fixed set of permissions (fixed permission JSON object) but a different secret for each deploy?

**Comment by sebadob** [comment]
I think they even must be separated, because they are handled differently inside.  
I need to take a quick look at the code am will get back at you.

**Comment by taladar** [comment]
At least for my Terraform use case building the JSON shouldn't be too hard since it has a `jsonencode` function even if they aren't separated but it might be cleaner for tools that do not have an equivalent functionality but just basic templating to build the environment variable templating (e.g. Helm).

**Comment by sebadob** [comment]
Yes I mean, you could even do this manually. Because I guess you would the same access rights each time anyway, like you mentioned.

**Comment by sebadob** [comment]
So, I could either accept it as bas64 which would make setting the env var easier, or accept a json directly, but then you have to carefully quote it and make sure there are no shell escapes or anything like that.

The Json I would try do deserialize into would be:

```rust
#[derive(Debug, Serialize, Deserialize, Validate, ToSchema)]
pub struct ApiKeyRequest {
    /// Validation: `^[a-zA-Z0-9_-/]{2,24}$`
    #[validate(regex(path = "RE_API_KEY", code = "^[a-zA-Z0-9_-/]{2,24}$"))]
    pub name: String,
    /// Unix timestamp in seconds in the future (max year 2099)
    #[validate(range(min = 1672527600, max = 4070905200))]
    pub exp: Option<i64>,
    pub access: Vec<ApiKeyAccess>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ToSchema)]
pub struct ApiKeyAccess {
    pub group: AccessGroup,
    pub access_rights: Vec<AccessRights>,
}
```

While the secret would need to be 64 random alnum characters.

**Comment by sebadob** [comment]
Giving the secret can be done as well, but you need to append the key id then manually. It is not just simply the secret, but it will contain the name as well in the format

```
let secret_fmt = format!("{}${}", name, secret_plain);
```

**Comment by taladar** [comment]
I think setting it as base64 encoded JSON would make things easier as you say. Quoting can be a bit of a nightmare when you have to use different quoting systems layered on top of each other (e.g. one in your templating, one in your config file format, one in shell code,...).

What would the name be in that case? And is there a required format for the secret?

**Comment by sebadob** [comment]
New config vars:

```
# You can provide an API Key during the initial prod database
# bootstrap. This key must match the format and pass validation.
# You need to provide it as a base64 encoded JSON in the format:
#
# ```
# struct ApiKeyRequest {
#     /// Validation: `^[a-zA-Z0-9_-/]{2,24}$`
#     name: String,
#     /// Unix timestamp in seconds in the future (max year 2099)
#     exp: Option<i64>,
#     access: Vec<ApiKeyAccess>,
# }
#
# struct ApiKeyAccess {
#     group: AccessGroup,
#     access_rights: Vec<AccessRights>,
# }
#
# enum AccessGroup {
#     Blacklist,
#     Clients,
#     Events,
#     Generic,
#     Groups,
#     Roles,
#     Secrets,
#     Sessions,
#     Scopes,
#     UserAttributes,
#     Users,
# }
#
# #[serde(rename_all = "lowercase")]
# enum AccessRights {
#     Read,
#     Create,
#     Update,
#     Delete,
# }
# ```
#
# You can use the `api_key_example.json` from `/` as
# an example. Afterwards, just `base64 api_key_example.json | tr -d '\n'`
BOOTSTRAP_API_KEY="ewogICJuYW1lIjogImJvb3RzdHJhcCIsCiAgImV4cCI6IDE3MzU1OTk2MDAsCiAgImFjY2VzcyI6IFsKICAgIHsKICAgICAgImdyb3VwIjogIkNsaWVudHMiLAogICAgICAiYWNjZXNzX3JpZ2h0cyI6IFsKICAgICAgICAicmVhZCIsCiAgICAgICAgImNyZWF0ZSIsCiAgICAgICAgInVwZGF0ZSIsCiAgICAgICAgImRlbGV0ZSIKICAgICAgXQogICAgfSwKICAgIHsKICAgICAgImdyb3VwIjogIlJvbGVzIiwKICAgICAgImFjY2Vzc19yaWdodHMiOiBbCiAgICAgICAgInJlYWQiLAogICAgICAgICJjcmVhdGUiLAogICAgICAgICJ1cGRhdGUiLAogICAgICAgICJkZWxldGUiCiAgICAgIF0KICAgIH0sCiAgICB7CiAgICAgICJncm91cCI6ICJHcm91cHMiLAogICAgICAiYWNjZXNzX3JpZ2h0cyI6IFsKICAgICAgICAicmVhZCIsCiAgICAgICAgImNyZWF0ZSIsCiAgICAgICAgInVwZGF0ZSIsCiAgICAgICAgImRlbGV0ZSIKICAgICAgXQogICAgfQogIF0KfQ=="

# The secret for the above defined bootstrap API Key.
# This must be at least 64 alphanumeric characters long.
# You will be able to use that key afterwards with setting
# the `Authorization` header:
#
# `Authorization: API-Key <your_key_name_from_above>$<this_secret>`
BOOTSTRAP_API_KEY_SECRET=twUA2M7RZ8H3FyJHbti2AcMADPDCxDqUKbvi8FDnm3nYidwQx57Wfv6iaVTQynMh
```

The `api_key_example.json`:

```json
{
  "name": "bootstrap",
  "exp": 1735599600,
  "access": [
    {
      "group": "Clients",
      "access_rights": [
        "read",
        "create",
        "update",
        "delete"
      ]
    },
    {
      "group": "Roles",
      "access_rights": [
        "read",
        "create",
        "update",
        "delete"
      ]
    },
    {
      "group": "Groups",
      "access_rights": [
        "read",
        "create",
        "update",
        "delete"
      ]
    }
  ]
}
```

When bootstrapped:

![grafik](https://github.com/sebadob/rauthy/assets/62848396/c763b051-feb0-41cc-9fc8-859bc222e153)

![grafik](https://github.com/sebadob/rauthy/assets/62848396/bbb68cfd-3ef8-4cfa-8963-9f2cd8a06396)

I guess that solves your problems. :)

**Comment by taladar** [comment]
I will test it tomorrow but it looks like what I need. Did you create another new image for testing or reuse the existing name you gave in the comment above?

**Comment by taladar** [comment]
Thank you for all the work you put into my use case.

**Comment by taladar** [comment]
Thank you, I will give it a try tomorrow and let you know how it goes.

**Comment by taladar** [comment]
I got it working now up to the point where I tested the API-Key with a curl command similar to yours above. Everything worked perfectly. Thank you again very much.

**Comment by sebadob** [comment]
Thanks for the feedback
