### ISSUE TITLE
Button labels are misplaced with chrome-based browsers

### ISSUE THREAD

**Issue by sebadob** [sebadob/rauthy#376]
I just found out that the Button labels are currently a bit out of place on chrome based browsers.  
I did not notice that lately since I am using Firefox only, where they are centered.

On chrome based browsers, they seem to have a bit too much `margin-top`. Wherever this is coming from, it should be fixed.

Firefox:

![grafik](https://github.com/sebadob/rauthy/assets/62848396/003429dd-a09b-4bfd-9ff3-fb748a6c7ca8)

Chromium:

![grafik](https://github.com/sebadob/rauthy/assets/62848396/9a13e15f-fe96-437b-b5b4-6af2fc4ecf2b)

**Comment by erlend-sh** [comment]
[Hardest Problem in Computer Science: Centering Things](https://tonsky.me/blog/centering/) 😁

**Comment by sebadob** [comment]
> [Hardest Problem in Computer Science: Centering Things](https://tonsky.me/blog/centering/) 😁

It really is -.-

I am trying to stay away from specific engine-native CSS as much as I can to avoid differences, but the button labels unfortunately are a bit tricky, because they can switch to the loading spinner internally... :D
