### ISSUE TITLE
Wrong OpenAPI Parameters in /oidc/rotateJwk and other handlers?

### ISSUE THREAD

**Issue by taladar** [sebadob/rauthy#397]
These contain

```
params(LogoutRequest),
```

in their utoipa definition which defines three path parameters that do not appear in the path, presumably this was meant to be a request body definition?

**Comment by taladar** [comment]
Korrektur, den Handlern nach sollte es ich hier um query und nicht path Parameter handeln.

**Comment by sebadob** [comment]
Right, these do appear wrongly in:
- `/oidc/rotateJwk`
- `/oidc/sessioninfo`
- `/oidc/sessioninfo/xsrf`

This is pretty annoying, that the `utoipa` macro can not check them. The `derive` macro for the `OpenApi` spec does validation though...

Thanks for spotting these. I will fix them soon.
