### ISSUE TITLE
Feat: Redirect client after registration to the origin client (uri)

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#401]
Registering a user should redirect him after registration to the original request.

Steps to reproduce/explain:
1. When using the `authorization_code` flow, the client gets redirect to the `/authorize` page and shows the login screen.
2. On that page there is a `User Registration` button, which redirects the user to the registration page.
3. After filling up that page, the user gets a confirmation mail which needs to be fulfilled with a password (or FIDO2).
4. After settings the password, the user gets redirected to the base url of the rauthy instance (with the rauthy client in the url).
5. When the user is now logging in, the user gets stuck on that application/client.

It would be awesome if a user could register an account (after pressing the `User Registration` button) and would be redirected to the same origin he came from (in that case the client_uri). Is it possible to redirect the user to the `redirect_uri`, `client_id`, `state` where the user came from?

The problem here is that we have a shop system where we have just a single `login` button on that page. And After that the user can see a `registration` button on the login page (which is awesome, thanks to #308 ), but After register their account, the user is not on the shop anymore and has no way to find back (except typing in the url).

Thank you very much for your time! :heart:

**Comment by sebadob** [comment]
I guess just re-using the already given `redirect_uri` if present should be enough to fix that, and it makes sense too.
I need to do some frontend work today anyway and will implement this.

**Comment by kerkmann** [comment]
Hi, sorry need to reopen it. Maybe it was a little bit misleading. I've created a video and on that video you can see a flow from a web shop, to the registration process and then the user is stuck in the `user account` dashboard.

The url flow is:
1. Click in [Our shop](https://moturbo.com/) on the `Anmelden` button (login), which doing an `authenticatin code flow` with a public client.
 2. hen click on the `User Registration` button on the [Login page](https://auth.moturbo.com/auth/v1/oidc/authorize?response_type=code&client_id=frontend&redirect_uri=https://moturbo.com/profile&scope=openid%20profile%20email%20groups&code_challenge=US-Kg2hUihr19q8IOl9fUlWqIC8BuuxR04-rwaVPqjc&code_challenge_method=S256) t
 3. You are getting redirected to the [registration page](https://auth.moturbo.com/auth/v1/users/register) and in the url you can see that the information of the `original client` and `redirect uri` gets lost.
 4. Type in your email and name for the registration.
 5. Open you mailbox and click on the [confirm the Email address](https://auth.moturbo.com/auth/v1/users/VyTIJOIXDKNd1zA3hCwzONWZ/reset/Dj7k8z2zl1QaNk2OwstAcW9vIcxbMFz9xSTV74T3biG2nnpAPeLKFspaC8rTPa21?type=new_user) link, set a password. (Here you can see as well that there are no information about the original client)
 6. then you are gettings redirected to the  [Authorize endpoint with the rauthy client](https://auth.moturbo.com/auth/v1/oidc/authorize?client_id=rauthy&redirect_uri=https%3A%2F%2Fauth.moturbo.com%2Fauth%2Fv1%2Foidc%2Fcallback&response_type=code&code_challenge=t7TKoayYpZyxe5BziggwfG3406t_-Fz3NkfVHkx9yg4&code_challenge_method=S256&scope=openid+profile+email&nonce=SNgYYQNbX47Z1SZ8wLt9OwoF&state=account) Here you can see that  the client is wrong, the original client was `frontend` and after setting the mail it's `rauthy`.
 7. After logging in the user gets redirected to the [User Account Dashboard](https://auth.moturbo.com/auth/v1/account)

The idea about this issue was that the user has a flow where he gets back to the shop itself. So the url of step `7` should be the original url of the original request. And I think the only way to do it properly is passing the `original client id` from `3` to step `6`. :)

I hope it's more clear and big thanks in advance! :heart: 

https://github.com/sebadob/rauthy/assets/1492139/bcc38858-673a-4330-bc45-bf42d46dc9c7

**Comment by kerkmann** [comment]
Should I reopen this issue or create a new one @sebadob ? :)

**Comment by sebadob** [comment]
... now I got what you meant. :)

This is fixes with the PR above for the registration.  
The password reset button there does not have such a functionality yet.

**Comment by sebadob** [comment]
Now it should be fixed for a password reset requested from the login form as well.

**Comment by kerkmann** [comment]
Awesome! I'll test it out this night. :)

**Comment by kerkmann** [comment]
It's working on my machine, Awesome. I would tell `rauthy` now production ready, you can customize it quit well and you are not stuck. :P

**Comment by sebadob** [comment]
Perfect, thank you!
As soon as I fixed the current openssl3 issue, I will release a `-beta2` and then probably `v0.23.0` soon.
