### ISSUE TITLE
bug (ui improvement): Delete a user resets the search filter in the Admin Users Dashbaord

### ISSUE THREAD

**Issue by kerkmann** [sebadob/rauthy#408]
In the [admin users dashboard](https://auth.moturbo.com/auth/v1/admin/users) you can filter user in the search area. After deleting a user from that list, the filter resets. The string is still in the search area, but the filter is not applied. Remove or adding one character to the filter updates the list again. :)

Nothing import, minor ui improvement. :D

**Comment by sebadob** [comment]
A general UI improvement and prettify is on the TODO. There are quite a few other small things currently that bug me with the UI.
