### ISSUE TITLE
New sorting options in admin area

### ISSUE THREAD

**Issue by timfvb** [sebadob/rauthy#413]
The possibility to filter by last login or account age in the admin user area would be very helpful.

Admin user area: `https://example.com/auth/v1/admin/users`

**Comment by sebadob** [comment]
The default sorting with the upcomping release will be by `created_at` column from the database.  
This is also the new stable index used for the dynamic server side pagination.

Currently, both fields `last_login` and `created_at` are not returning when you just fetch all users, but only a very minimal version with `id` and `email` to still keep big instances fast.

With the new server side pagination coming in `v0.23.0`, I can add more stuff to the returned value while still keeping big instances fast. This ordering only works on the client side though, to it currently only works for "all existing users" at the same time, when you have the full database inside the UI, not only a part of it from server side pagination.

I am thinking about adding some more analytics / insight view in the future, which can filter for more things while limiting the data returned from the backend, so you would not get 100k users back for big instances.
