### ISSUE TITLE
Support W3C DID

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sebadob/rauthy#511]
Hi,

Do you think it may possible to add support of [W3C DID](https://www.w3.org/TR/did-core/) and include [DID-Web](https://w3c-ccg.github.io/did-method-web/) and if possible [DID peer](https://identity.foundation/peer-did-method-spec/)

Thank you,

**Comment by sebadob** [comment]
Hey,

since I never worked with DIDs before or have any use for them, could you please explain what you mean with support for them, which is pretty generic?  
What is your desired outcome, what purpose should something like this serve, so I can understand it better?

**Comment by MarcAntoine-Arnaud** [comment]
Hi,

That can make sense, it's used for [dataspace](https://internationaldataspaces.org/).
I'm quite new into it, but it's relevant for our project as partner of [TEMS](https://tems-dataspace.eu/).

Some documentation is provided by Eclipse foundation [here](https://github.com/eclipse-edc/Publications/blob/main/Identity%20Management/DID_EDC.md)

I have found also relevant information [here](https://techcommunity.microsoft.com/t5/microsoft-entra-blog/identity-hubs-as-personal-datastores/ba-p/389577)
And a technical page [here](https://tsmatz.wordpress.com/2019/12/24/decentralized-identifiers-did-tutorial/)

So one first question is the valuation of the complexity to handle that standard and be compliant as IdentityHub in a dataspace ecosystem.

Regards,
Marc-Antoine

**Comment by sebadob** [comment]
I took at look at the RFC, but I still don't get it what you want to achieve with them in the combination with Rauthy, what purpose should they fulfill?

Should they serve the current JWKS from the OIDC spec as DID's, or do you want user information as DIDs, kind of like the current `webid` feature?

I got it what DID's are, but not how you want to use them with Rauthy, in which context. I need to know the bigger picture.

From the RFC:

> A [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers) refers to any subject (e.g., a person, organization, thing, data model, abstract entity, etc.) as determined by the controller of the [DID](https://www.w3.org/TR/did-core/#dfn-decentralized-identifiers).

So, they can be anything. What do you expect them to be in combination with Rauthy?
