### ISSUE TITLE
REST API normalize case convention

### ISSUE THREAD

**Issue by polarathene** [sebadob/rauthy#536]
Presently if looking over the endpoints from the Swagger docs, there is some inconsistency here. Might be worthwhile to normalize to `kebab-case` which is generally most appropriate for URLs?

Some endpoints are using `snake_case` and `camelCase`, and from the looks of it some like `sessioninfo` perhaps should be `session-info`?

**Comment by sebadob** [comment]
Yes, that is on the TODO for the next smaller release.

I will deprecate any inconsistent endpoints and keep them around for 1 release so make any migrations easy.
