### ISSUE TITLE
feedback: Bootstrap permissions

### ISSUE THREAD

**Issue by polarathene** [sebadob/rauthy#540]
I have been meaning to write up an issue about this, but still caught up with my backlog elsewhere. I may come back to revise this, but I did want to provide feedback on the [current implementation of `BOOTSTRAP_API_KEY`](https://sebadob.github.io/rauthy/config/bootstrap.html#api-key).

The base64 approach makes sense as an ENV value, but becomes a bit clunky the larger the JSON to encode. Adjusting it while experimenting (_due to defaults not being sufficient_) also adds a bit of friction.

I was curious if the JSON could be provided directly as a file. In some projects an ENV has a `__FILE` suffix or detects the value as a filepath to support reading contents from a file instead. Usually it's for secrets that you would prefer to restrict access to (_instead of visibility to all processes that can check the ENV_).

In this case it's also preferable to not have such a file required to be base64 encoded. While not a major DX issue (_I can use the `base64` command with a shell script to update an ENV file each time_), considering how the feature is limited to only the bootstrap feature, it would be nicer if tweaking the permissions was more seamless to iterate without the base64 roundtrip?

The other feedback I had for this was that the ENV name `BOOTSTRAP_API_KEY` itself didn't quite reflect what the value represented. In actual usage with the Authorization header we use `bootstrap$<secret>`. It is more like `BOOTSTRAP_API_ACL`?

**Comment by polarathene** [comment]
> What exactly do you mean with it, adjusting / experimenting? Do you mean adjust the proper access rights you need to set to be able to do everything you need, or are you having issues with the JSON structure itself?

My memory on the concern is a bit vague, it was 2 weeks or so ago. I remember getting the demo setup how I wanted it and then automating the UI steps away via API calls, but those needed additional permissions. There was no export via the UI, nor could I modify the bootstrap permissions IIRC, so I just edited the JSON, base64 encoded again and restarted the container.

I only did that a few times iteratively, I don't have a strong use-case for direct file support avoiding any extra base64 dance if I want to include the JSON as a separate file for an example, rather than commit a large base64 blob in an `.env` file or `compose.yaml`. The examples are intended as minimal intervention to demonstrate integrating with an IdP, rather than a production guide for rauthy.

---

For reference, the `compose.yaml` setup is fairly minimal for rauthy, and besides the `BOOTSTRAP_API_KEY` value, the only real verbosity/friction for getting a minimal integration demonstrated is the API calls below (_which I can minimize further_).

These are how I have them presently, when I return to wrap it up I'll [share the full reference to my original discussion](https://github.com/sebadob/rauthy/discussions/270) (_where your guidance was much appreciated_ ❤️ )

<details>
<summary>Create client</summary>

```bash
curl --silent --request POST \
  --url "${BASE_URL}/auth/v1/clients" \
  --header 'Authorization: API-Key bootstrap$twUA2M7RZ8H3FyJHbti2AcMADPDCxDqUKbvi8FDnm3nYidwQx57Wfv6iaVTQynMh' \
  --header 'Content-Type: application/json' \
  --data '{
  "confidential": true,
  "id": "roundcube",
  "name": "Webmail Roundcube",
  "redirect_uris": [
    "https://rc.example.localhost/index.php/login/oauth"
  ]
}'
```

</details>

<details>
<summary>Adjust the client config</summary>

Opt-out of PKCE challenge (not supported) + add `client_credentials` flow:

```bash
# Could probably simply with a GET + jq to modify the JSON body to send:
curl --silent --request PUT \
  --url "${BASE_URL}/auth/v1/clients/roundcube" \
  --header 'Authorization: API-Key bootstrap$twUA2M7RZ8H3FyJHbti2AcMADPDCxDqUKbvi8FDnm3nYidwQx57Wfv6iaVTQynMh' \
  --header 'Content-Type: application/json' \
  --data '{
  "id": "roundcube",
  "name": "Webmail Roundcube",
  "enabled": true,
  "confidential": true,
  "redirect_uris": [
    "https://rc.example.localhost/index.php/login/oauth"
  ],
  "flows_enabled": [
    "authorization_code",
    "client_credentials",
    "refresh_token"
  ],
  "access_token_alg": "EdDSA",
  "id_token_alg": "EdDSA",
  "auth_code_lifetime": 60,
  "access_token_lifetime": 1800,
  "scopes": [
    "openid",
    "email",
    "profile",
    "groups"
  ],
  "default_scopes": [
    "openid"
  ],
  "force_mfa": false,
  "client_uri": null,
  "contacts": null,
  "challenges": null
}'
```

</details>

<details>
<summary>Get client secret</summary>

```bash
# Slightly awkward way to update client secret for app to query rauthy,
# since rauthy does not support providing an externally generated secret.
# Non-issue with a real production setup.
curl --silent --request POST \
  --url "${BASE_URL}/auth/v1/clients/roundcube/secret" \
  --header 'Authorization: API-Key bootstrap$twUA2M7RZ8H3FyJHbti2AcMADPDCxDqUKbvi8FDnm3nYidwQx57Wfv6iaVTQynMh' \
| jq -r .secret \
| sed -i -r "s|^(RC_OAUTH2__CLIENT_SECRET=).*|\1$(cat -)|" ./secrets.env
```

</details>

**Comment by sebadob** [comment]
> My memory on the concern is a bit vague, it was 2 weeks or so ago. I remember getting the demo setup how I wanted it and then automating the UI steps away via API calls, but those needed additional permissions. There was no export via the UI, nor could I modify the bootstrap permissions IIRC, so I just edited the JSON, base64 encoded again and restarted the container.

Okay, got it.  
In the docs, the API Key being bootstrapped is just an example, not a default by any means. Which access rights you add in the JSON array heavily depend on what you need to do with it. So from your example, you would want `create`, `read` and `update` for clients. But I guess you figured that out by now, because Rauthy will mention the missing access rights in the error response when they are not sufficient with your currently used API Key.

There is no export function in the UI, that's true. That could be a nice feature in the future. I have a "prettify UI" on the TODO which is one of the bigger leftover TODOs before I can release v1.0.0. Originally I wanted to rebuild the whole UI using Leptos, but I am not absolutely sure yet if it is actually worth all the time, because the current Svelte UI is super efficient and works pretty good. Fine-tuning the current UI and probably migrating to Svelte 5 would be a lot less work.
I will do the UI part as soon as I have stabilized and integrated [Hiqlite](https://github.com/sebadob/hiqlite) into Rauthy. I can add an export easily, even both in a plain and b64 encoded version.

Btw you don't need to include `null` values in your PUT client JSON above. If they do not exist at all, Rauthy will assume they are `null` by default.

**Comment by sebadob** [comment]
Closing it since this is not really an issue.
