### ISSUE TITLE
auth_time in id_token does not conform to OIDC standard

### ISSUE THREAD

**Issue by gilliangoud** [sebadob/rauthy#554]
I've been having some trouble with the package [oidc-client-ts](url)

I've been receiving the error "" upon renew of the token. The package expects upon token renew the auth_time of the new id_token to be the exact same as the auth_time of the first issued id_token as per spec: [https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse)

It seems Rauthy sends the time of authentication as the auth_time instead of the time of initial authentication when SESSION_LIFETIME is not defined.
https://github.com/sebadob/rauthy/blob/bd47f42d1d0b97ee4760efbb26ebbf22af5aee94/src/service/src/token_set.rs#L228

For reference, I've been using the Admin account on version 24.1 and 25.0 sqlite docker image.

How much work would it be to implement the 'more accurate time' as describe in code comments for the id token creation?

**Comment by sebadob** [comment]
Thanks for the issue. 

I am currently in the middle of a big cache migration under the hood, but I had a quick look. Yes it's true, that it will always re-calculate instead of re-using the original `auth_time` when it's a refresh. I will fix this.

The amount of work is not too big. I will probably finish the cache migration today (hopefully) and then can fix this.

**Comment by sebadob** [comment]
I build a nightly image which includes the fix. You can test with the tags 

- `0.26.0-20240905`
- `0.26.0-20240905-lite`

This nightly image also includes a pretty big internal migration of the cache layer, so if you stumble about any issues in this regard, please let me though. I haven't found any problems though so far.

**Comment by gilliangoud** [comment]
Wow! Initial usage of the nightly seems to completely solve the problem I'm having; thanks so much.

The alternate solution I had come up with last night was to make the token validity exactly 60 seconds longer than the SESSION_LIFETIME environment variable. Very niche and very specific to the package I'm using; which refreshes the token 60 seconds before it expires... :)

**Comment by sebadob** [comment]
Thanks for the feedback.

I already had the changes to get a 100% correct `auth_time` from a few releases ago. I just had to do these changes and fixes in a few steps and it has not been done in this last instance yet. I also added an integrations test for make sure the `auth_time` will always be properly handled in refresh scenarios.
