### ISSUE TITLE
UserResponse.created_at described as string in openapi spec, but api return number

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#586]
In v0.24.1 (and v0.25.0 I think too) it seems like the components.schemas.UserResponse.properties.created_at is of type "string" in spec, but when querying the `/user/email/{email}` endpoint, created_at is returned as a number.

**Comment by sebadob** [comment]
Thanks!

Yes that obviously is a bug. The `str` there is a leftover from when I returned String-formatted `Date`s.
It may be possible that such values exist on other response types as well, I need to double check that.

Basically, whenever you expect any Timestamp, Expiry, or anything like that, Rauthy will always return the Unix Timestamp in Seconds.
