### ISSUE TITLE
Rauthy does not shut down upon SIGTERM when metrics server is enabled

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#589]
Using v0.25.0-lite it seems like rauthy does a graceful shutdown when receiving SIGTERM as printed in logs, however if the METRICS_ENABLED configuration is true, it seems to execute some of the shutdown sequence, but continues running until process is killed after the accept thread is stopped as reported by the logs

<details>

<summary> Log with METRICS_ENABLED=true </summary>

```
2024-10-14T11:13:43.129175Z  INFO actix_server::server: SIGTERM received; starting graceful shutdown
2024-10-14T11:13:43.129196Z  INFO actix_server::server: SIGTERM received; starting graceful shutdown
2024-10-14T11:13:43.129245Z  INFO actix_server::accept: accept thread stopped
2024-10-14T11:13:43.129246Z  INFO actix_server::worker: shutting down idle worker
2024-10-14T11:13:43.129299Z  INFO actix_server::worker: graceful worker shutdown; finishing 2 connections
2024-10-14T11:13:43.129307Z  INFO actix_server::accept: accept thread stopped
2024-10-14T11:13:45.133587Z  INFO rauthy_middlewares::logging: 172.20.0.32 HTTP/2.0 POST /auth/v1/oidc/token "Go-http-client/2.0"
... continues until process is killed
```

</details>

<details>

<summary> Log with METRICS_ENABLED=false </summary>

and SWAGGER_UI_INTERNAL and EXTERNAL = false

```
2024-10-14T11:11:08.915316Z  INFO actix_server::server: SIGTERM received; starting graceful shutdown
2024-10-14T11:11:08.915379Z  INFO actix_server::worker: graceful worker shutdown; finishing 2 connections
2024-10-14T11:11:08.915398Z  INFO actix_server::accept: accept thread stopped
<process is shut down>
```
</details>

**Comment by sebadob** [comment]
It can't have anything to do with the metrics, because I am running with metrics all the time and never had that issue.
But more important:

Does this happen on `0.26` too and is it reproducable?

I had this situation a few times in the past with Hiqlite and am trying since then to find a way to reproduce this, but haven't seen it in quite a while, especially after the latest (blind) fixes for this. But... 0.25 does not use Hiqlite at all yet. Could it also be that this is somehow related to your environment?

**Comment by andoks** [comment]
> It can't have anything to do with the metrics, because I am running with metrics all the time and never had that issue. But more important:

Weird, that seems to be the only difference in the configuration that triggers it for me

> Does this happen on `0.26` too and is it reproducable?

I will report back when I test it with 0.26

> I had this situation a few times in the past with Hiqlite and am trying since then to find a way to reproduce this, but haven't seen it in quite a while, especially after the latest (blind) fixes for this. But... 0.25 does not use Hiqlite at all yet. Could it also be that this is somehow related to your environment?

Could be related to my environment for sure. I am running rauthy inside a docker-compose configuration.

**Comment by andoks** [comment]
You were right in that it (with high probability) is not related to METRICS or enabled or not.

In docker-compose, when shutting down services, the default compose waits for a service before sending it SIGKILL is 10 seconds after sending it SIGINT/SIGTERM. It seems like rauthy too has such a timeout internally somewhere (maybe one of these https://github.com/search?q=repo%3Asebadob%2Frauthy%20from_secs(10)&type=code ?), and so it seems like it becomes a race between docker and rauthy who hits the timeout first, which rauthy loses more often than not on my setup, leading I suspect to rauthy being sigkilled most of the time. I think I am ok with simply increasing the timout for rauthy in my compose config though.

If this seems realistic to you, I am ready to close this issue. (all of this on v0.25.0 BTW)

**Comment by sebadob** [comment]
Oh, if your docker compose does an auto-kill after a timeout, there is a high chance that this produces some conflicts.

Rauthy has internal timeouts, waits for some things to finish like ongoing web-requests, if schedulers are currently running, and most importantly, it will try to do a graceful switch in HA deployments if the current instance is the leader, if a database backup is currently running, and many more. You will start to notice this timeout probably a bit more when using the Hiqlite version. It introduces shutdown delays on purpose to have smoother leader switches in HA scenarios and rolling releases when deployed inside K8s.

Sending a SIGKILL after 10 seconds is pretty quick and I would bump this value up to something like 60. It could take some time depending on what state the application is currently in.

**Comment by andoks** [comment]
That sounds reasonable. I adjusted the timeout to 20 seconds as I'm running a single instance configuration, but maybe I should consider increasing it further. Anyway I consider this resolved, thank your for the help (and a great software) yet again =)
