### ISSUE TITLE
Feature Request: format logs as json or logfmt

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#590]
For consuming and parsing the logs, it would be great if it was possible to tell rauthy to format them as either json (my preference) or in logfmt format.

From some quick searching around it seems like the tracing library used in rauthy [supports it](https://users.rust-lang.org/t/best-way-to-log-with-json/83385/2).

**Comment by sebadob** [comment]
Done. Some things will not be nicely parseable, at least for now. For instance, an internal `Event` will be formatted as Text output, or in other places in `debug` log level, the Text output will log JSON already, which would be double-escaped. But for the most part, it should be fine I guess.

**Comment by andoks** [comment]
Awesome, thanks! I will try to give it a spin as soon as the v0.27.0 docker image is released :-) (for now I have not gotten around to build image from source. Maybe I should give that a go).

**Comment by sebadob** [comment]
> Maybe I should give that a go

Should be pretty easy, I hope. If you have troubles please let me know. I always try to set up everything easily usable.
The [CONTRIBUTING.md](https://github.com/sebadob/rauthy/blob/main/CONTRIBUTING.md) should give you all the information you need.

**Comment by andoks** [comment]
Seems like the json logs works quite well :slightly_smiling_face: 

Obviously [the banner](https://github.com/sebadob/rauthy/blob/43b6f00ecdb885814d1988df94329d31f25c2511/src/bin/src/main.rs#L52) is not valid JSON though, could perhaps a flag be added to skip it, or always skip it when LOG_FMT=json? Or even maybe use the standard log facilities to print it? This way I don't need to be aware of certain lines not being parsable as json, and any lines that fail may be considered a bug in either the parsing or in rauthy (or somewhere in between)

**Comment by sebadob** [comment]
Yes sure, I already thought about adding such a variable to opt-out of it. Thats a tiny thing to add.
Haven't tried if using the default logging would break the format, need to check that.
