### ISSUE TITLE
run on kubernetes  Pod Terminated with 139

### ISSUE THREAD

**Issue by zzl221000** [sebadob/rauthy#598]
```
CrashLoopBackOff (back-off 10s restarting failed container=rauthy pod=rauthy-0_rauthy(8fb376da-7437-4f5c-8916-e1cece8ccf39)) | Last state: Terminated with 139: Error, started: Thu, Oct 24 2024 5:19:22 pm, finished: Thu, Oct 24 2024 5:19:23 pm
```
kubernetes and os version
```
v1.26.13+k3s1
CentOS Linux 8
containerd://1.7.11-k3s2.26
```

**Comment by zzl221000** [comment]
Hmm... I carefully reviewed the documentation and checked the configuration in the config, and I missed `LISTEN_SCHEME=http`.
Perhaps it would be better to have a separate text block for required configuration fields in the documentation.

**Comment by sebadob** [comment]
> Perhaps it would be better to have a separate text block for required configuration fields in the documentation.

Usually, you only need to copy & paste the [reference config](https://sebadob.github.io/rauthy/config/config.html) and adjust it to your needs. It has all the mandatory and the likely-to-change variables out-commented by default.

I mention to copy the reference into place for both docker and kubernetes getting started, but I'm glad it's resolved.

**Comment by zzl221000** [comment]
Thank you for developing such a great project; I really like it!

**Comment by sebadob** [comment]
> Thank you for developing such a great project; I really like it!

Thanks! :)
