### ISSUE TITLE
Unable to connect to SMTP

### ISSUE THREAD

**Issue by morki** [sebadob/rauthy#613]
I have some hard time connecting to SMTP server, it always fail with:

```
rauthy-1  | 2024-11-12T09:11:10.979125Z  WARN rauthy_models::email: Could not connect to mail.morki.cz:465 via TLS. Trying downgrade to STARTTLS
rauthy-1  | 2024-11-12T09:11:10.979249Z ERROR rauthy_models::email: Could not connect to mail.morki.cz:465 via STARTTLS either
rauthy-1  | 2024-11-12T09:11:10.979273Z ERROR rauthy_models::email: ErrorResponse { timestamp: 1731402670, error: Internal, message: "Could not connect to mail.morki.cz:465 - neither TLS nor STARTTLS worked" }
```

I have many other docker images with the same setting and on the same network, which are working correctly.

Can you please take a look? I can create you a testing email on my server if that helps to debug the issue.

**Comment by sebadob** [comment]
Remove the port from the url and try again. Rauthy will choose default ports, starts with TLS as the most secure option and will then downgrade to STARTTLS if that is not successful. But you do not need to provde the port and I never had issues with SMTP so far.
