### ISSUE TITLE
Non ASCII characters not supported in some places

### ISSUE THREAD

**Issue by morki** [sebadob/rauthy#614]
My given name is "Lukáš", but I cannot use it in Rauthy, because only ASCII strings are supported it seems.

![image](https://github.com/user-attachments/assets/ffed58b8-65f7-4534-966c-40ddf483d15a)

**Comment by sebadob** [comment]
Oh, that's a frontend validation bug, because the backend allows them:

`[a-zA-Z0-9À-ÿ-\s]{1,32}`

In which module in the UI do you get this error?

**Comment by sebadob** [comment]
Actually, the `š` is the issue as it seems to be not covered by `À-ÿ`.

I don't know about your alphabet, but if you could give me a list with the unicode variants of all missing characters, I could add them.

**Comment by sebadob** [comment]
> I don't think this is the right way to do. What about chinese and Japanese people etc?

Asian characters are included in the regex above.

> What is the reason to even limit human readable name to regex?

The values are almost always displayed to the user in some form. Rauthy itself never inserts data into the DOM as HTML, but client applications may do this, when they grab the data from tokens. No a single value that you can submit to Rauthy's API will be unvalidated or just taken as it is, except from a password, which will be hashed right away anyway.

> I understand this for system values, but it does not make sense here I think.

It makes sense in the way that it will prevent people from choosing absolute nonsense names, or simply an Emoji as their name. Usually, `À-ÿ` should cover all special characters in the western alphabet, I didn't even know about the `š`.

> The same should apply to Client human readable name etc.

It does already, the client name regex is very similar to the user names.

**Comment by sebadob** [comment]
Okay, I checked this and the default JS `À-ÿ` actually ends right before quite a few characters you need, but it also includes some already. At first glance, I guess it would be fine for you if I include `Latin Extended-A` like [shown here](https://symbl.cc/en/unicode/blocks/latin-extended-a/)?

This could be done very simply by adding the range `\u0100-\u017F`.

**Comment by sebadob** [comment]
Simply expanding the existing regex from `À-ÿ` to `À-ſ` was enough to include them.

**Comment by sebadob** [comment]
@morki you could do testing with the latest nightly I just built, if you like:

```
ghcr.io/sebadob/rauthy:0.27.0-20241118
```

The whole database layer has been changed a lot, so you might take a look at the *Unreleased* section of the [CHANGELOG.md](https://github.com/sebadob/rauthy/blob/main/CHANGELOG.md) if you have issues. However, it should (hopefully) work right out of the box, if you are not using Postgres currently.

**Comment by sebadob** [comment]
It should not have broken everything, only the login with webauthn, because I forgot to add a check for the configured DB in the auth finish step.

With `ghcr.io/sebadob/rauthy:0.27.0-20241119`, everything should be good now.

If something else is broken with the image from today, please let me know. The tansaction is fixed.

**Comment by lnicola** [comment]
Probably U+0218 to U+021B, I didn't check the others. But it would probably make sense to include the whole Latin Extended-B block.
