### ISSUE TITLE
[BUG] Allowed to create user with a single-character family name, but not save modifications to it

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#633]
When I created an ad-hoc user for testing some stuff, I created it with the family_name set to "X" (as in the single character). I was allowed to create this user fine, but when I subsequently wanted to edit it in the web UI, no changes to  the account was applied, and I could not see any error messages in the UI.

In the browser debug console however, I go the message `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

And when check the actual network request sent to Rauthy backend from the frontend, i found that the requests' response-body was: `Validation errors in fields: 	family_name: Validation error: [a-zA-Z0-9À-ÿ-\s]{2,128} [{"value": String("X")}]`

**Comment by sebadob** [comment]
Yes, that was a mismatch between UI validation for better UX and backend validation.

The `family_name` has been made completely optional just today and the mismatch in the UI validation has been fixed for both given and family name in #631.
