### ISSUE TITLE
v0.27.0 Bumps openapi standard in use from v3.0.3 to v3.1.0

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#638]
As v0.27.0 Bumps openapi standard in use from v3.0.3 to v3.1.0 in the Rauthy API spec, it might be worth adding to release notes along the breaking changes.

An issue for me in particular since I use a code-generator that unfortunately doesn't support v3.1, only 3.0, but hopefully I will get around that (specifically oapi-codegen: https://github.com/oapi-codegen/oapi-codegen/issues/373).

Just wanted to give a heads up =)

**Comment by sebadob** [comment]
Oh, that's good to know.
I wasn't aware that this would break something, thought it would only add features. I rarely use OpenAPI docs.

The API itself has not changed though, it's only the spec, so you could use 0.26.2 for code gen.

I will add it to the release notes, thank you.

**Comment by andoks** [comment]
It is possible to generate client code for Go with https://openapi-generator.tech/ instead of oapi-codegen
