### ISSUE TITLE
OpenAPI specification for /clients endpoint specifies only a single object as result

### ISSUE THREAD

**Issue by andoks** [sebadob/rauthy#639]
For the GET on `/clients` it seems like the result is specified in the OpenAPI spec as 

```openapi
"application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientResponse"
                }

```

When it should be
```openapi
"application/json": {
                "schema": {
                  "items": {
                    "$ref": "#/components/schemas/ClientResponse"
                  },
                  "type": "array"
                }
```

Or an additional definition for `ClientsResponse` or `ClientResponses`?

**Comment by sebadob** [comment]
Yes, this is the case in a few places. When I added `utoipa` for OpenAPI gen it was not possible to declare Arrays / Vec's. 
But I think it is by now. I will check this and fix it in some other places too.
